remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  hide_site_feed_link: true
  social_links:
    - title: +KZ Discord Server
      icon: discord
      url: "https://discord.gg/nt8aStQxcR"
    - title: Buy me a coffee
      icon: circle-dollar-to-slot
      url: "https://ko-fi.com/pluskaizo"

