remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  title: +KZ Website
  skin: dark
  hide_site_feed_link: true
  social_links:
    - title: +KZ Discord Server
      icon: discord
      url: "/discord.html"

